pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        APPVERSION=''
        REGION='us-east-1'
        ACCOUNT_ID='515138251473'
        PROJECT='roboshop'
        COMPONENT='cart'
    }
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('get code') {
            steps {
                git url: 'https://github.com/meghashyam-singh/7-4.git', branch: 'main'
            }
        }
        stage('read version') {
            steps {
                dir('cart') {
                    script {
                        def node = readJSON file: 'package.json'
                        APPVERSION = node.version
                        echo "APPVERSION IS: ${APPVERSION}"
                    }
                }
            }
        }
        stage('build') {
            steps {
                dir('cart') {
                    sh "npm install"
                }
            }
        }
        stage('sonar scan') {
            environment {
                def scannerHome = tool 'sonar-8.0'
            }
            steps {
                dir('cart') {
                    script {
                        withSonarQubeEnv('sonar-server') {
                        sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }
        stage('quality gates') {
            steps {
                timeout(time:1, unit:'HOURS')
                waitForQualityGate() abortPipeline = true
            }
        }
        stage('image-build') {
            steps {
                sh "docker build -t ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ./cart"
            }
        }
        stage('image scan') {
            steps {
                sh "trivy image ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} >> cart-image-scan.txt"
            }
        }
        stage('image push') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                    aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
                    docker tag ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    """
                }
            }
        }
    }
}