pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        APPVERSION=''
        PROJECT='roboshop'
        COMPONENT='catalogue'
        REGION='us-east-1'
        ACCOUNT_ID='515138251473'
    }
    stages {
        stage('clean') {
            steps {
                cleanWs()
            }
        }
        stage('checkout scm') {
            steps {
                git url: 'https://github.com/meghashyam-singh/7-4.git', branch: 'main'
            }
        }
        stage('read version') {
            steps {
                dir('catalogue') {
                    script {
                        def pom = readJSON file: 'package.json'
                        APPVERSION = pom.version
                        echo "APPVERSION IS: ${APPVERSION}"
                    }
                }
            }
        }
        stage('build') {
            steps {
                dir('catalogue') {
                    sh "npm install"
                }
            }
        }
        stage('image build') {
            steps {
                sh "docker build -t ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ./catalogue"
            }
        }
        stage('image scan') {
            steps {
                sh "trivy image ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} >> catalogue-image-scan.txt"
            }
        }
        stage('image-push') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                    aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
                    docker tag ${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APPVERSION}-${BUILD_NUMBER}
                    """
                }
            }
        }
    }
}